name: Release

on:
  release:
    branches: 
    - main
    types: [published]

env:
  VERBOSITY:  'Normal'
  CONFIGURATION: 'Release'
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  Release:
    name: Release Build TinyCLR 
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Extract build information into variables
      id: info
      run: |
        echo "##[set-output name=version;]$(echo $env:GITHUB_REF.Replace('refs/tags/v',''))"
        echo "##[set-output name=build;]$(echo $(git rev-list --count HEAD))"
        echo "##[set-output name=copyright;]$(echo © $(date -u +%Y) Bytewizer.  All rights reserved.)" 
    
    - name: Show build information
      run: |
        echo build=${{ steps.info.outputs.build }}
        echo copyright=${{ steps.info.outputs.copyright }}

    - name: Show release event information
      run: |
        echo "release.name        = ${{ github.event.release.name }}"
        echo "release.body        = ${{ github.event.release.body }}"
        echo "release.upload_url  = ${{ github.event.release.upload_url }}"
        echo "release.html_url    = ${{ github.event.release.html_url }}"
        echo "release.tag_name    = ${{ github.event.release.tag_name }}"
        echo "release.draft       = ${{ github.event.release.draft }}"
        echo "release.prerelease  = ${{ github.event.release.prerelease }}"
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64     
    
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest' 

    - name: Setup nanoFramework
      uses: nanoframework/nanobuild@v1

    - name: Restore TinyCLR project
      working-directory: src
      run: >- 
        msbuild Bytewizer.TinyCLR.Drivers.Blues.Notecard.sln -t:restore -verbosity:${env:VERBOSITY} 

    - name: Restore NanoCLR project
      working-directory: src
      run: >- 
        nuget restore Bytewizer.NanoCLR.Drivers.Blues.Notecard.sln

    - name: Release build and pack TinyCLR libraries
      working-directory: src
      run: >- 
        msbuild Bytewizer.TinyCLR.Drivers.Blues.Notecard.sln -t:pack -verbosity:${env:VERBOSITY}
        -p:PackageOutputPath=\builds\artifacts
        -p:BuildNumber="${{ steps.info.outputs.build }}"
        -p:Copyright="${{ steps.info.outputs.copyright }}"
        -p:VersionPrefix="${{ steps.info.outputs.version }}"
        -p:PackageVersion="${{ steps.info.outputs.version }}"
        -p:Configuration=${env:CONFIGURATION}
        -p:ContinuousIntegrationBuild=true
   
    - name: Release build and pack NanoCLR libraries
      working-directory: src
      run: >- 
        msbuild Bytewizer.NanoCLR.Drivers.Blues.Notecard.sln -t:pack -verbosity:${env:VERBOSITY}
        -p:PackageOutputPath=\builds\artifacts
        -p:BuildNumber="${{ steps.info.outputs.build }}"
        -p:Copyright="${{ steps.info.outputs.copyright }}"
        -p:VersionPrefix="${{ steps.info.outputs.version }}"
        -p:PackageVersion="${{ steps.info.outputs.version }}"
        -p:Configuration=${env:CONFIGURATION}
        -p:ContinuousIntegrationBuild=true

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Release Packages
        path: \builds\artifacts
    
    - name: Create release asset
      run: Compress-Archive -DestinationPath \builds\nuget-packages.zip -Path \builds\artifacts\*.*nupkg
      
    - name: Upload release asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: \builds\nuget-packages.zip
        asset_name: Packages
        asset_content_type: application/zip
        
    - name: Publish package to github.com
      run: |    
        nuget sources add -name github.com -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -username ${{ github.actor }} -password ${{secrets.PACKAGE_API_KEY}}
        nuget push \builds\artifacts\**\*.nupkg -source github.com -apikey ${{secrets.PACKAGE_API_KEY}} -skipduplicate

    - name: Publish package to nuget.org
      run: |
        nuget push \builds\artifacts\**\*.nupkg -source nuget.org -apikey ${{secrets.NUGET_API_KEY}} -skipduplicate
